services:
  Wvision\Bundle\DataDefinitionsBundle\Interpreter\CoreShop\PriceInterpreter:
    tags:
      - { name: data_definitions.interpreter, type: coreshop_price, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Interpreter\CoreShop\PriceInterpreterType }

  Wvision\Bundle\DataDefinitionsBundle\Setter\CoreShop\StorePriceSetter:
    arguments:
      - '@coreshop.repository.store'
    tags:
      - { name: data_definitions.setter, type: coreshop_store_price, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Setter\CoreShop\StorePriceSetterType }
      - { name: data_definitions.getter, type: coreshop_store_price, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Setter\CoreShop\StorePriceSetterType }

  importdefinitions.coreshop.setter.store_values: '@Wvision\Bundle\DataDefinitionsBundle\Setter\CoreShop\StoreValuesSetter'
  Wvision\Bundle\DataDefinitionsBundle\Setter\CoreShop\StoreValuesSetter:
    arguments:
      - '@coreshop.repository.store'
    tags:
      - { name: data_definitions.setter, type: coreshop_store_values, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Setter\CoreShop\StoreValuesSetterType }
      - { name: data_definitions.getter, type: coreshop_store_values, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Setter\CoreShop\StoreValuesSetterType }


  Wvision\Bundle\DataDefinitionsBundle\Interpreter\CoreShop\StoresInterpreter:
    tags:
      - { name: data_definitions.interpreter, type: coreshop_stores, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Interpreter\CoreShop\StoresInterpreterType }

  Wvision\Bundle\DataDefinitionsBundle\Interpreter\CoreShop\CurrencyInterpreter:
    arguments:
      - '@coreshop.repository.currency'
    tags:
      - { name: data_definitions.interpreter, type: coreshop_currency, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\NoConfigurationType }

  Wvision\Bundle\DataDefinitionsBundle\Interpreter\CoreShop\MoneyInterpreter:
    arguments:
      - '@coreshop.repository.currency'
    tags:
      - { name: data_definitions.interpreter, type: coreshop_money, form-type: Wvision\Bundle\DataDefinitionsBundle\Form\Type\Interpreter\CoreShop\MoneyInterpreterType }
